spring.h2.console.enabled=true
spring.h2.console.path=/h2-console



server.port=${PORT:8080}



spring.datasource.url=jdbc:postgresql://dpg-d74iip4r85hc73fqu8ng-a:5432/kyc_service
spring.datasource.username=root
spring.datasource.password=KTZHj6AgowZJtWU6pGh63QKNWBdXPY3e

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
